// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxN5z9oAIjJMYHp2loqnle4jL67TkVQs',
    appId: '1:197533783060:android:30000a4acdfb55c34f4301',
    messagingSenderId: '197533783060',
    projectId: 'physioappnew',
    storageBucket: 'physioappnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmbERceI4sdFm9X9F6hO6NcdM9GxNlVOQ',
    appId: '1:197533783060:ios:bfd4062f3d1a05b94f4301',
    messagingSenderId: '197533783060',
    projectId: 'physioappnew',
    storageBucket: 'physioappnew.appspot.com',
    androidClientId: '197533783060-3idlgdis766esie7mt8ig5eknqa0rhvm.apps.googleusercontent.com',
    iosClientId: '197533783060-1qndhjo6p1tv3fkh1sk00l8n1lkh8tkh.apps.googleusercontent.com',
    iosBundleId: 'com.personal.hopewell',
  );
}
